# https://github.com/treosh/lighthouse-ci-action

name: Lighthouse
on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build --if-present
      - name: Run Lighthouse against static public directory
        uses: treosh/lighthouse-ci-action@v9
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          configPath: '.github/workflows/lighthouserc.json'
